baseURL = 'https://toolkit.design/'
languageCode = 'en-nz'
title = 'Toolkit.design'
theme = 'toolkit-theme'

[Params]
  description = "Toolkit.design"
  images = ['/digital-garden-logo.png']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'All resources'
  url = '/resources'
  weight = 2

[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com'
  weight = 1
[[menu.social]]
  name = 'RSS'
  url = '/resources/index.xml'
  weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true